### ISSUE TITLE
Question about building this program

### ISSUE THREAD

**Issue by WilliamWangPeng** [darekjk/roughsets-base#1]
HI dear author,
    It's an honor to write the issue here, I'm building this program nowadays, but can't compile successfully, the errors are as following:
    I use $ pip install test , but pip shows there remains no test module. and the other errors are hard to fix. My GPU is NVIDIA A100,  Driver Version: 510.47.03    CUDA Version: 11.6

![image](https://user-images.githubusercontent.com/51076736/155288216-3ef9f9cb-0ebc-4609-ad3c-5ff6279b8107.png)

![image](https://user-images.githubusercontent.com/51076736/155288281-1fead456-8134-41f3-898c-42241a8c3b8f.png)

```
wangpeng@amax:~/tools/test/roughsets-base-master$ ./run_tests.sh 
ROUGHSETS_KDD99_TEST_DATA_FOLDER = /home/wangpeng/tools/test/roughsets-base-master/tests/datasets/KDD99
Building ...
/usr/bin/python: No module named build
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    from pip import main
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 22, in <module>
    from pip._vendor.requests.packages.urllib3.exceptions import DependencyWarning
  File "/usr/lib/python2.7/dist-packages/pip/_vendor/__init__.py", line 64, in <module>
    vendored("distro")
  File "/usr/lib/python2.7/dist-packages/pip/_vendor/__init__.py", line 33, in vendored
    __import__(modulename, globals(), locals(), level=0)
  File "/usr/share/python-wheels/distro-1.0.1-py2.py3-none-any.whl/distro.py", line 1051, in <module>
  File "/usr/share/python-wheels/distro-1.0.1-py2.py3-none-any.whl/distro.py", line 595, in __init__
  File "/usr/share/python-wheels/distro-1.0.1-py2.py3-none-any.whl/distro.py", line 934, in _get_lsb_release_info
subprocess.CalledProcessError: Command 'lsb_release -a' returned non-zero exit status 1
Running unit tests ...
EEEEE
======================================================================
ERROR: test_dataset_KDD99 (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_dataset_KDD99
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/home/wangpeng/tools/test/roughsets-base-master/tests/test_dataset_KDD99.py", line 46
SyntaxError: Non-ASCII character '\xc2' in file /home/wangpeng/tools/test/roughsets-base-master/tests/test_dataset_KDD99.py on line 46, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details


======================================================================
ERROR: test_dataset_3 (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_dataset_3
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/home/wangpeng/tools/test/roughsets-base-master/tests/test_dataset_3.py", line 13
    def tearDown(self) -> None:
                       ^
SyntaxError: invalid syntax


======================================================================
ERROR: test_t_abstract_base (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_t_abstract_base
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/home/wangpeng/tools/test/roughsets-base-master/tests/test_t_abstract_base.py", line 1, in <module>
    from pandas import Int64Index
ImportError: No module named pandas


======================================================================
ERROR: test_dataset_2 (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_dataset_2
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/home/wangpeng/tools/test/roughsets-base-master/tests/test_dataset_2.py", line 14
    def tearDown(self) -> None:
                       ^
SyntaxError: invalid syntax


======================================================================
ERROR: test_dataset_1 (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_dataset_1
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/home/wangpeng/tools/test/roughsets-base-master/tests/test_dataset_1.py", line 14
    def tearDown(self) -> None:
                       ^
SyntaxError: invalid syntax


----------------------------------------------------------------------
Ran 5 tests in 0.000s

FAILED (errors=5)
Running flake8 tests ...
./run_tests.sh: line 22: flake8: command not found
Running tox tests ...
wangpeng@amax:~/tools/test/roughsets-base-master$ 

```

thank you
best regards
William

**Comment by darekjk** [comment]
Hi,

according to your errors, I guess yuo use Python 2. The library is designed to work with Python 3 (v.3.8+ recommended).
Before you run tests you need to install additional libraries:
pip install -r requirements.dev.txt

Best regards,
Dariusz Jankowski
